# Generated by versionbump.py 2016-11-05 12:35:36.269258
major = 0
minor = 6
patch = 1
status = "d"
build = ""
name = ""


def get_release():
    r = "%s.%s.%s" % (major, minor, patch)

    if status:
        r += "-%s" % status

    return r


def get_version():
    return "%s.%s" % (major, minor)


RELEASE = get_release()
VERSION = get_version()

